import type { ModelResult } from "./model-result.interface";
import type { ResponseMetadata } from "./response-metadata.interface";

/**
 * Interface representing the response received from an AI model. This interface provides
 * methods to access the main result or a list of results generated by the AI model, along
 * with the response metadata. It serves as a standardized way to encapsulate and manage
 * the output from AI models, ensuring easy retrieval and processing of the generated
 * information.
 *
 * @typeParam T - the type of the result(s) provided by the AI model
 */
export interface ModelResponse<T extends ModelResult<unknown>> {
  /**
   * Retrieves the (first) result of the AI model.
   * @returns the result generated by the AI model
   */
  get result(): T | null;

  /**
   * Retrieves the list of generated outputs by the AI model.
   * @returns the list of generated outputs
   */
  get results(): T[];

  /**
   * Retrieves the response metadata associated with the AI model's response.
   * @returns the response metadata
   */
  get metadata(): ResponseMetadata;
}
