packages:
  - 'packages/*'
  - 'packages/mcp/*'
  - 'packages/vector-stores/*'
  - 'packages/memory/repository/*'
  - 'packages/models/*'
  - 'packages/advisors/*'
  - 'packages/document-readers/*'

onlyBuiltDependencies:
  - '@nestjs/core'
  - 'sharp'
