export const CHAT_MODEL_TOKEN = Symbol.for("CHAT_MODEL_TOKEN");
export const CHAT_CLIENT_BUILDER_TOKEN = Symbol.for(
  "CHAT_CLIENT_BUILDER_TOKEN",
);
export const CHAT_CLIENT_CUSTOMIZER_TOKEN = Symbol.for(
  "CHAT_CLIENT_CUSTOMIZER_TOKEN",
);
export const HTTP_CLIENT_TOKEN = Symbol.for("HTTP_CLIENT_TOKEN");
export const METER_REGISTRY_TOKEN = Symbol.for("METER_REGISTRY_TOKEN");
export const OBSERVATION_REGISTRY_TOKEN = Symbol.for(
  "OBSERVATION_REGISTRY_TOKEN",
);
