export const CHAT_MODEL_TOKEN = Symbol.for("CHAT_MODEL_TOKEN");
export const CHAT_MEMORY_TOKEN = Symbol.for("CHAT_MEMORY_TOKEN");
export const EMBEDDING_MODEL_TOKEN = Symbol.for("EMBEDDING_MODEL_TOKEN");
export const BATCHING_STRATEGY_TOKEN = Symbol.for("BATCHING_STRATEGY_TOKEN");
export const VECTOR_STORE_TOKEN = Symbol.for("VECTOR_STORE_TOKEN");
export const CHAT_CLIENT_BUILDER_TOKEN = Symbol.for(
  "CHAT_CLIENT_BUILDER_TOKEN",
);
export const CHAT_CLIENT_CUSTOMIZER_TOKEN = Symbol.for(
  "CHAT_CLIENT_CUSTOMIZER_TOKEN",
);
export const HTTP_CLIENT_TOKEN = Symbol.for("HTTP_CLIENT_TOKEN");
export const METER_REGISTRY_TOKEN = Symbol.for("METER_REGISTRY_TOKEN");
export const OBSERVATION_REGISTRY_TOKEN = Symbol.for(
  "OBSERVATION_REGISTRY_TOKEN",
);
export const PROVIDER_INSTANCE_EXPLORER_TOKEN = Symbol.for(
  "PROVIDER_INSTANCE_EXPLORER_TOKEN",
);
