/*
 * Copyright 2023-present the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import {
  AssistantMessage,
  type Message,
  type MessageType,
} from "@nestjs-ai/model";

/**
 * An atomic unit in the session's conversation history.
 *
 * `SessionEvent` is a _thin wrapper_ around the existing NestJS AI {@link Message}
 * types. There is no duplication of content structures — the existing `UserMessage`,
 * `AssistantMessage`, `SystemMessage`, and `ToolResponseMessage` classes carry the
 * actual content. `SessionEvent` adds only what {@link Message} intentionally lacks:
 * identity, ordering, session-level provenance, and agent-branch attribution.
 *
 * The wrapped {@link Message} already encodes the event type via its {@link MessageType}:
 * - `UserMessage` → user input
 * - `AssistantMessage` (no tool calls) → agent response
 * - `AssistantMessage` (with tool calls) → tool invocation
 * - `ToolResponseMessage` → tool output
 * - `UserMessage` + {@link isSynthetic} → synthetic shadow prompt that opens a summary turn
 * - `AssistantMessage` + {@link isSynthetic} → compaction summary text that closes a summary turn
 *
 * Events are immutable once created (append-only log semantics). Use {@link builder}
 * to construct instances.
 */
export class SessionEvent {
  /** Metadata key for the `synthetic` flag (value: `boolean`). */
  static readonly METADATA_SYNTHETIC = "synthetic";

  /** Metadata key identifying which compaction strategy produced a synthetic event. */
  static readonly METADATA_COMPACTION_SOURCE = "compactionSource";

  private readonly _id: string;
  private readonly _sessionId: string;
  private readonly _timestamp: Date;
  private readonly _message: Message;
  private readonly _metadata: Record<string, unknown>;
  private readonly _branch: string | null;

  constructor(builder: SessionEventBuilder) {
    assert(builder.idValue.length > 0, "id must not be null or empty");
    assert(
      builder.sessionIdValue.length > 0,
      "sessionId must not be null or empty",
    );
    assert(builder.timestampValue != null, "timestamp must not be null");
    assert(builder.messageValue != null, "message must not be null");
    this._id = builder.idValue;
    this._sessionId = builder.sessionIdValue;
    this._timestamp = builder.timestampValue;
    this._message = builder.messageValue;
    this._metadata = { ...builder.metadataValue };
    this._branch = builder.branchValue;
  }

  /** Unique identity per event. {@link Message} has none. */
  get id(): string {
    return this._id;
  }

  /** Session ownership and isolation. */
  get sessionId(): string {
    return this._sessionId;
  }

  /** Chronological ordering within the session. */
  get timestamp(): Date {
    return this._timestamp;
  }

  /** The actual NestJS AI message — no duplication of content. */
  get message(): Message {
    return this._message;
  }

  /**
   * Session-level flags: {@link METADATA_SYNTHETIC}, {@link METADATA_COMPACTION_SOURCE},
   * etc.
   */
  get metadata(): Record<string, unknown> {
    return this._metadata;
  }

  /**
   * Dot-separated agent hierarchy path that produced this event (e.g.
   * `"orchestrator.researcher"`). `null` for root-level events that predate any
   * delegation. Used by `EventFilter.forBranch(string)` to isolate peer sub-agents'
   * histories from each other.
   */
  get branch(): string | null {
    return this._branch;
  }

  /**
   * Returns `true` if this event belongs to the root conversation thread, i.e. was not
   * produced inside any delegated sub-agent branch. Root events have a `null` branch.
   * @returns `true` if this event is a root-level event, `false` otherwise
   */
  isRootEvent(): boolean {
    return this._branch === null;
  }

  /**
   * Convenience accessor — delegates to the wrapped message. No need to unwrap for common
   * type-switch operations.
   */
  get messageType(): MessageType {
    return this._message.messageType;
  }

  /**
   * Returns `true` for events generated by the framework (e.g. compaction summaries), not
   * by a real user/agent turn.
   */
  isSynthetic(): boolean {
    return (
      (this._metadata[SessionEvent.METADATA_SYNTHETIC] as boolean) ?? false
    );
  }

  /**
   * Returns `true` for assistant messages that include tool invocations. Delegates to
   * {@link AssistantMessage.hasToolCalls} — no separate event type needed.
   */
  hasToolCalls(): boolean {
    return (
      this._message instanceof AssistantMessage && this._message.hasToolCalls()
    );
  }

  /** Returns a new {@link SessionEventBuilder} for constructing a {@link SessionEvent}. */
  static builder(): SessionEventBuilder {
    return new SessionEventBuilder();
  }
}

/**
 * Builder for {@link SessionEvent}.
 *
 * Defaults: `id` is auto-generated (random UUID), `timestamp` is the current instant,
 * `metadata` is empty, `branch` is `null`. `sessionId` and `message` are required.
 */
export class SessionEventBuilder {
  private _idValue: string = randomUUID();
  private _sessionIdValue = "";
  private _timestampValue: Date = new Date();
  private _messageValue: Message | null = null;
  private _metadataValue: Record<string, unknown> = {};
  private _branchValue: string | null = null;

  get idValue(): string {
    return this._idValue;
  }

  get sessionIdValue(): string {
    return this._sessionIdValue;
  }

  get timestampValue(): Date {
    return this._timestampValue;
  }

  get messageValue(): Message | null {
    return this._messageValue;
  }

  get metadataValue(): Record<string, unknown> {
    return this._metadataValue;
  }

  get branchValue(): string | null {
    return this._branchValue;
  }

  /** Overrides the auto-generated event ID. */
  id(id: string): this {
    this._idValue = id;
    return this;
  }

  /** The session this event belongs to. Required. */
  sessionId(sessionId: string): this {
    this._sessionIdValue = sessionId;
    return this;
  }

  /** Overrides the default timestamp (the current instant). */
  timestamp(timestamp: Date): this {
    this._timestampValue = timestamp;
    return this;
  }

  /** The NestJS AI message wrapped by this event. Required. */
  message(message: Message): this {
    this._messageValue = message;
    return this;
  }

  /** Replaces the entire metadata map. */
  metadata(metadata: Record<string, unknown>): this;
  /** Adds a single metadata entry. */
  metadata(key: string, value: unknown): this;
  metadata(
    metadataOrKey: Record<string, unknown> | string,
    value?: unknown,
  ): this {
    if (typeof metadataOrKey === "string") {
      this._metadataValue[metadataOrKey] = value;
    } else {
      this._metadataValue = { ...metadataOrKey };
    }
    return this;
  }

  /**
   * The dot-separated agent path that produced this event. Pass `null` (the default) for
   * root-level events.
   */
  branch(branch: string | null): this {
    this._branchValue = branch;
    return this;
  }

  /** Builds the {@link SessionEvent}, validating required fields. */
  build(): SessionEvent {
    return new SessionEvent(this);
  }
}
