import type { ResultMetadata } from "../model/result-metadata.interface.js";

/**
 * An interface that represents metadata associated with the results of a moderation
 * generation process. This interface extends the ResultMetadata interface, which provides
 * general information about the results generated by an AI model.
 */
export interface ModerationGenerationMetadata extends ResultMetadata {}
